

GET http://localhost:3001/api/users HTTP/1.1

####

POST  http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
  "email": "jacskonrico@gmail.com",
  "password": "password"
}
###

POST  http://localhost:3001/api/register HTTP/1.1
Content-Type: application/json

{
  "name": "Rico Jackson",
  "lastname": "rico",
  "email": "jacksonrico@gmail.com",
  "password": "password",
  "username": "ricojackson"
}